#!/bin/bash
MAPPINGS="/root/.mappings";
while IFS= read -r LINE
do
	TOKENS=(${LINE//:/ });  
	LOCAL_PART=${TOKENS[0]};
    BUCKET_PART=${TOKENS[1]};
	aws s3 sync --region eu-central-1 "$LOCAL_PART" s3://"$BUCKET_PART";
done < "$MAPPINGS";
echo "Sync-up completed";
